# tis script is to calcualte the absolute coordinates of bodyparts determined via DeepLabCut and the gradient at these coordinates

In [3]:
#Import packages
import pandas as pd
from pathlib import Path
import numpy as np
import os
import matplotlib.pyplot as plt
from natsort import natsorted
import glob
import matplotlib.patches as patches
import coordinate_conversion_functions as coord_conv
import curve_fitting_functions as curve_fit
import fnmatch
from collections import OrderedDict
from track_plotting_daniel import *

## centroid coordinates (output from micromanager)

In [18]:
path_center_coords='/groups/zimmer/Ulises/wbfm/chemotaxis_assay/2020_Only_behaviour/all_tracks/2020-07-01_13-21-00_chemotaxisl_worm1-TablePosRecord.txt'
center_coords=pd.read_csv(path_center_coords)
center_coords.head()

           time  xc        x  yc        y
0  13:21:00.988   x  21.3617   y  12.4125
1  13:21:05.079   x  21.6873   y  12.3068
2  13:21:05.095   x  21.6873   y  12.3068
3  13:21:05.095   x  21.6873   y  12.3068
4  13:21:05.095   x  21.6873   y  12.3068

## realtive coordinates of bodyparts determined via DLC

In [32]:
path_bodypart_coords='/groups/zimmer/Ulises/wbfm/chemotaxis_assay/2020_Only_behaviour/avi_all/2020-07-01_13-21-00_chemotaxisl_worm1-channel-0-bigtiffDLC_resnet50_HeadTailAug10shuffle1_275000_filtered.h5'
bodypart_coords=pd.read_hdf(path_bodypart_coords, low_memory=False)
bodypart_coords.head()

scorer    DLC_resnet50_HeadTailAug10shuffle1_275000                         \
bodyparts                                      Head
coords                                            x           y likelihood
0                                        335.493225  279.720947   0.885174
1                                        335.850616  291.608521   0.914306
2                                        336.320496  291.608521   0.901548
3                                        337.016968  291.608521   0.915392
4                                        337.677704  291.608521   0.915135

scorer
bodyparts        Tail
coords              x           y likelihood
0          322.490356  360.631958   0.928813
1          323.039917  361.555389   0.775067
2          323.086639  361.555389   0.816025
3          323.304199  361.555389   0.818554
4          323.348816  361.574158   0.838415

In [33]:
len(bodypart_coords)

200001

## get the absolute position of bodyparts

#### define parameters

In [20]:
px_mm=0.00325 # this value represents how much mm is one pixel
x_lenght_frame=608 #lenght of x axis in frame in recording used for DLC (measured with fiji)
y_width_frame=610 #width of the y axis in frame

#### calculate absolute head and tail positon

In [21]:
df_head_tail_center_coords=coord_conv.get_absolute_bodypart_coordinates(center_coords,bodypart_coords,px_mm,y_width_frame,x_lenght_frame)
df_head_tail_center_coords.head()

,absolute_x_Head,absolute_y_Head,absolute_x_Tail,absolute_y_Tail,x_center,y_center
0,21.259347,12.330343,21.301606,12.593304,21.3617,12.4125
1,21.583785,12.263278,21.625420,12.490605,21.6873,12.3068
2,21.582258,12.263278,21.625268,12.490605,21.6873,12.3068
3,21.579995,12.263278,21.624561,12.490605,21.6873,12.3068
4,21.577847,12.263278,21.624416,12.490666,21.6873,12.3068

## correct for food position
sets the coordinate of the food patch to 0
(x_ref measured manually after each recording)

In [22]:
#correct for food position
x_ref=8.7#9.10
df_head_tail_center_coords=coord_conv.adjust_for_food_position(df_head_tail_center_coords,x_ref)
df_head_tail_center_coords.head()

,absolute_x_Head,absolute_y_Head,absolute_x_Tail,absolute_y_Tail,x_center,y_center
0,12.559347,12.330343,12.601606,12.593304,12.6617,12.4125
1,12.883785,12.263278,12.925420,12.490605,12.9873,12.3068
2,12.882258,12.263278,12.925268,12.490605,12.9873,12.3068
3,12.879995,12.263278,12.924561,12.490605,12.9873,12.3068
4,12.877847,12.263278,12.924416,12.490666,12.9873,12.3068

## calculate gradient exposure of bodyparts
(parameters obtained by fitting a curve to bromophenol diffusion on agar (4h)--> see curve_fit script)

In [23]:
#quadratic
a=0.00675494
b=-0.16437685
c=1

In [24]:
#exponential
y0=1         
plateau=0
K=0.23754334

In [25]:
#sigmoid
L=1
x0=3.81953189
k=-0.69421567
b=0

In [26]:
df_head_tail_center_coords=coord_conv.calculate_concentration_for_bodyparts(df_head_tail_center_coords.copy(),'sigmoid',L,x0,k,b)
df_head_tail_center_coords.head()

,absolute_x_Head,absolute_y_Head,absolute_x_Tail,absolute_y_Tail,x_center,y_center,concentration_absolute_x_Head,concentration_absolute_x_Tail,concentration_x_center
0,12.559347,12.330343,12.601606,12.593304,12.6617,12.4125,0.002312,0.002245,0.002154
1,12.883785,12.263278,12.925420,12.490605,12.9873,12.3068,0.001847,0.001794,0.001719
2,12.882258,12.263278,12.925268,12.490605,12.9873,12.3068,0.001849,0.001794,0.001719
3,12.879995,12.263278,12.924561,12.490605,12.9873,12.3068,0.001851,0.001795,0.001719
4,12.877847,12.263278,12.924416,12.490666,12.9873,12.3068,0.001854,0.001795,0.001719

## calculate concentration change from one frame to the next

In [27]:
#add columns with difference in concentration for all bodyparts

#get concentration columns
all_bodyparts_concentration=df_head_tail_center_coords[df_head_tail_center_coords.columns[pd.Series(df_head_tail_center_coords.columns).str.contains('concentration')]]

#add new columns with change in concentration
for current_bodypart in all_bodyparts_concentration.columns:
        df_head_tail_center_coords[f'change_in_{current_bodypart}']=all_bodyparts_concentration[current_bodypart].diff()

## adding a column representing time passed (in seconds)

In [28]:
#add a column displaying time
fps=167 #frames per second
df_head_tail_center_coords['seconds']=np.arange(0, len(df_head_tail_center_coords)/fps,1/fps)
df_head_tail_center_coords

,absolute_x_Head,absolute_y_Head,absolute_x_Tail,absolute_y_Tail,x_center,y_center,concentration_absolute_x_Head,concentration_absolute_x_Tail,concentration_x_center,change_in_concentration_absolute_x_Head,change_in_concentration_absolute_x_Tail,change_in_concentration_x_center,seconds
0,12.559347,12.330343,12.601606,12.593304,12.6617,12.4125,0.002312,0.002245,0.002154,NaN,NaN,NaN,0.000000
1,12.883785,12.263278,12.925420,12.490605,12.9873,12.3068,0.001847,0.001794,0.001719,-0.000465,-4.512226e-04,-0.000435,0.005988
2,12.882258,12.263278,12.925268,12.490605,12.9873,12.3068,0.001849,0.001794,0.001719,0.000002,1.887970e-07,0.000000,0.011976
3,12.879995,12.263278,12.924561,12.490605,12.9873,12.3068,0.001851,0.001795,0.001719,0.000003,8.793819e-07,0.000000,0.017964
4,12.877847,12.263278,12.924416,12.490666,12.9873,12.3068,0.001854,0.001795,0.001719,0.000003,1.803949e-07,0.000000,0.023952
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199997,0.488273,16.671920,0.702163,16.455699,0.3021,16.3923,0.909916,0.896981,0.919964,-0.000138,0.000000e+00,0.000000,1197.586826
199998,0.492050,16.671920,0.702063,16.455100,0.3020,16.3923,0.909701,0.896988,0.919969,-0.000215,6.414774e-06,0.000005,1197.592814
199999,0.493533,16.668119,0.701963,16.455100,0.3019,16.3923,0.909616,0.896994,0.919974,-0.000085,6.414420e-06,0.000005,1197.598802
200000,0.496709,16.667919,0.701863,16.455000,0.3018,16.3922,0.909435,0.897001,0.919979,-0.000181,6.414067e-06,0.000005,1197.604790
200001,NaN,NaN,NaN,NaN,0.3017,16.3921,NaN,NaN,0.919984,NaN,NaN,0.000005,1197.610778

## save dataframe as csv

In [30]:
#save as csv
output_path='/groups/zimmer/Daniel_Mitic/data/'
filename='2020-07-01_13-21-00_chemotaxisl_worm1.csv'
print(output_path+filename)
df_head_tail_center_coords.to_csv(output_path+filename)

/groups/zimmer/Daniel_Mitic/data/2020-07-01_13-21-00_chemotaxisl_worm1.csv

## all the steps above but for all recordings

### define paths and read in csv containing x_refs for all recordings as a column

In [31]:
path='/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/'
output_path='/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/body_part_coordinates/'
all_x_ref=pd.read_csv('/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/all_x_refs.csv')
all_x_ref.head()

                                                name  x_ref
0  2020-07-01_10-10-48_control_worm1-TablePosReco...   7.64
1  2020-07-01_10-50-18_control_worm2-TablePosReco...   7.64
2  2020-07-01_11-50-53_control_worm3-TablePosReco...   7.64
3  2020-07-01_13-21-00_chemotaxisl_worm1-TablePos...   9.00
4  2020-07-01_14-41-11_chemotaxisl_worm2-TablePos...  10.50

### define parameters needed for calculating absolute coordinates of the bodyparts

In [ ]:

px_mm=0.00325 # this value represents how much mm is one pixel total_lenght_mm/total_lengt_pixel
x_lenght_frame=608 #lenght of x axis in frame (measured with fiji)
y_width_frame=610 #width of the y axis in frame
fps=167

### loop to create csv with absolute coordinates of bodyparts + x_ref correction

In [34]:


for i, folder in enumerate(natsorted(os.listdir(path))):
    
    #stop the loop when last x_ref has been reached
    if i>len(all_x_ref)-1:break
    
    #get current x_ref
    x_ref=all_x_ref['x_ref'][i] 
    print(i, ': x ref of ', folder, 'is: ', x_ref)
    
    #get bodypart coordinates from DeepLabCut
    hdf5_files=glob.glob(os.path.join(path,folder,'*.h5'))
    hdf5_file=hdf5_files[0]
    bodypart_coords=pd.read_hdf(hdf5_file)
    
    #get centroid coordinates from micromanager
    txt_files=glob.glob(os.path.join(path,folder,'*.txt'))
    txt_file=txt_files[0]
    center_coords=pd.read_csv(txt_file)
   
    
    #some center coordinates have more rows than dlc data. this checks and adjusts the lenght of the centroid coordinates 
    if len(center_coords) > len(bodypart_coords):
        rows_diff=len(center_coords) - len(bodypart_coords)
        print(txt_files,'is',rows_diff,' rows longer')
        center_coords.drop(center_coords.tail(rows_diff).index,inplace=True)
    center_coords = center_coords[0:len(bodypart_coords)] 
    
    
    
    #get absolute coordinates for the bodyparts
    df_head_tail_center_coords=coord_conv.get_absolute_bodypart_coordinates(center_coords,bodypart_coords,px_mm,y_width_frame,x_lenght_frame)
    
    #adjust for food position
    df_head_tail_center_coords=coord_conv.adjust_for_food_position(df_head_tail_center_coords,x_ref)
    
    #add column with time passed
    df_head_tail_center_coords['seconds']=np.arange(0, len(df_head_tail_center_coords)/fps,1/fps)
    
    #save as csv
    #df_head_tail_center_coords.to_csv(output_path+folder+'_bodypart_coordinates.csv')

0 : x ref of  2020-07-01_10-10-48_control_worm1-TablePosRecord is:  7.639999999999999
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_10-10-48_control_worm1-TablePosRecord/2020-07-01_10-10-48_control_worm1-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             13.962351        24.376240        14.905561        23.993702
1             13.862682        24.426580        14.801465        24.028304
2             13.862595        24.426580        14.799063        24.028875
3             13.862499        24.426580        14.799063        24.028987
4             13.861733        24.426580        14.799063        24.029305
...                 ...              ...              ...              ...
199996        24.163553        10.062531        24.393371         9.274600
199997        24.163453        10.062551        24.393419         9.275000
199998        24.163253        10.062951        24.394458         9.275282
199999        24.163153        10.062624        24.394976         9.275682
200000        24.163053        10.061371        24.396835         9.275982

        x_center  y_center      seconds
0        14.4167   24.2157     0.000000
1        14.3175   24.2502     0.005988
2        14.3175   24.2502     0.011976
3        14.3175   24.2502     0.017964
4        14.3175   24.2502     0.023952
...          ...       ...          ...
199996   24.3057    9.5953  1197.580838
199997   24.3056    9.5957  1197.586826
199998   24.3054    9.5961  1197.592814
199999   24.3053    9.5965  1197.598802
200000   24.3052    9.5968  1197.604790

[200001 rows x 7 columns]
1 : x ref of  2020-07-01_10-50-18_control_worm2-TablePosRecord is:  7.639999999999999
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_10-50-18_control_worm2-TablePosRecord/2020-07-01_10-50-18_control_worm2-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             19.295462        19.291871        19.385838        18.263900
1             19.271849        19.546872        19.355156        18.516492
2             19.271327        19.547111        19.355156        18.516627
3             19.269677        19.547111        19.355156        18.516802
4             19.269529        19.547122        19.354827        18.516979
...                 ...              ...              ...              ...
199996         2.163113         6.398077         2.821431         6.113103
199997         2.162613         6.397239         2.821191         6.113103
199998         2.162113         6.396691         2.822143         6.113203
199999         2.161613         6.395461         2.821787         6.113303
200000         2.161113         6.394987         2.822144         6.113403

        x_center  y_center      seconds
0        19.4090   18.7377     0.000000
1        19.3863   18.9896     0.005988
2        19.3863   18.9896     0.011976
3        19.3863   18.9896     0.017964
4        19.3863   18.9896     0.023952
...          ...       ...          ...
199996    2.5263    6.3256  1197.580838
199997    2.5258    6.3256  1197.586826
199998    2.5253    6.3257  1197.592814
199999    2.5248    6.3258  1197.598802
200000    2.5243    6.3259  1197.604790

[200001 rows x 7 columns]
2 : x ref of  2020-07-01_11-50-53_control_worm3-TablePosRecord is:  7.639999999999999
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             19.761030        16.282056        20.309815        17.052432
1             19.753083        16.294974        20.305510        17.059555
2             19.753043        16.295322        20.303935        17.060016
3             19.753043        16.296018        20.303935        17.060016
4             19.752643        16.295718        20.303535        17.059716
...                 ...              ...              ...              ...
199996         2.560724        13.421141         2.574525        13.429466
199997         2.560924        13.421041         2.574725        13.429366
199998         2.561124        13.421041         2.574925        13.429366
199999         2.563618        13.416356         2.575125        13.428836
200000         2.568180        13.413071         2.575425        13.428736

        x_center  y_center      seconds
0        19.9232   16.6004     0.000000
1        19.9232   16.6004     0.005988
2        19.9232   16.6004     0.011976
3        19.9232   16.6004     0.017964
4        19.9228   16.6001     0.023952
...          ...       ...          ...
199996    2.7604   13.4297  1197.580838
199997    2.7606   13.4296  1197.586826
199998    2.7608   13.4296  1197.592814
199999    2.7610   13.4296  1197.598802
200000    2.7613   13.4295  1197.604790

[200001 rows x 7 columns]
3 : x ref of  2020-07-01_13-21-00_chemotaxisl_worm1-TablePosRecord is:  9.0
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_13-21-00_chemotaxisl_worm1-TablePosRecord/2020-07-01_13-21-00_chemotaxisl_worm1-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             12.259347        12.330343        12.301606        12.593304
1             12.583785        12.263278        12.625420        12.490605
2             12.582258        12.263278        12.625268        12.490605
3             12.579995        12.263278        12.624561        12.490605
4             12.577847        12.263278        12.624416        12.490666
...                 ...              ...              ...              ...
199996         0.185842        16.672020         0.402163        16.455799
199997         0.188273        16.671920         0.402163        16.455699
199998         0.192050        16.671920         0.402063        16.455100
199999         0.193533        16.668119         0.401963        16.455100
200000         0.196709        16.667919         0.401863        16.455000

        x_center  y_center      seconds
0        12.3617   12.4125     0.000000
1        12.6873   12.3068     0.005988
2        12.6873   12.3068     0.011976
3        12.6873   12.3068     0.017964
4        12.6873   12.3068     0.023952
...          ...       ...          ...
199996    0.0021   16.3924  1197.580838
199997    0.0021   16.3923  1197.586826
199998    0.0020   16.3923  1197.592814
199999    0.0019   16.3923  1197.598802
200000    0.0018   16.3922  1197.604790

[200001 rows x 7 columns]
4 : x ref of  2020-07-01_14-41-11_chemotaxisl_worm2-TablePosRecord is:  10.5
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_14-41-11_chemotaxisl_worm2-TablePosRecord/2020-07-01_14-41-11_chemotaxisl_worm2-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             14.962800        15.022802        16.040837        15.092046
1             14.810655        14.990773        15.887005        15.059743
2             14.810535        14.992948        15.887005        15.060383
3             14.810414        14.993450        15.887005        15.060505
4             14.810314        14.995230        15.886905        15.060579
...                 ...              ...              ...              ...
199996        -0.216802        26.147656         0.091517        25.106452
199997        -0.216802        26.147756         0.091581        25.106552
199998        -0.216802        26.147856         0.091646        25.106535
199999        -0.216842        26.147410         0.091546        25.106166
200000        -0.216298        26.147410         0.091606        25.105324

        x_center  y_center      seconds
0        15.4866   15.1372     0.000000
1        15.3373   15.1046     0.005988
2        15.3373   15.1046     0.011976
3        15.3373   15.1046     0.017964
4        15.3372   15.1046     0.023952
...          ...       ...          ...
199996   -0.0166   25.6222  1197.580838
199997   -0.0166   25.6223  1197.586826
199998   -0.0166   25.6224  1197.592814
199999   -0.0167   25.6224  1197.598802
200000   -0.0167   25.6224  1197.604790

[200001 rows x 7 columns]
5 : x ref of  2020-07-01_15-13-35_chemotaxisl_worm3-TablePosRecord is:  8.1
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_15-13-35_chemotaxisl_worm3-TablePosRecord/2020-07-01_15-13-35_chemotaxisl_worm3-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             16.904568        14.362464        16.150421        13.634613
1             16.898568        14.370169        16.144781        13.642267
2             16.898199        14.370918        16.144700        13.642358
3             16.896848        14.372060        16.144413        13.642490
4             16.895381        14.372808        16.144033        13.642490
...                 ...              ...              ...              ...
199996        15.027315        18.374463        15.032990        18.081827
199997        15.027315        18.374563        15.033227        18.081306
199998        15.027315        18.374563        15.033227        18.081306
199999        15.027215        18.374663        15.033127        18.081406
200000        15.028085        18.374663        15.033127        18.081238

        x_center  y_center      seconds
0        16.4786   13.9748     0.000000
1        16.4733   13.9824     0.005988
2        16.4733   13.9824     0.011976
3        16.4733   13.9824     0.017964
4        16.4733   13.9824     0.023952
...          ...       ...          ...
199996   15.2074   18.1772  1197.580838
199997   15.2074   18.1773  1197.586826
199998   15.2074   18.1773  1197.592814
199999   15.2073   18.1774  1197.598802
200000   15.2073   18.1774  1197.604790

[200001 rows x 7 columns]
6 : x ref of  2020-07-01_15-42-06_chemotaxisl_worm4-TablePosRecord is:  7.8
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_15-42-06_chemotaxisl_worm4-TablePosRecord/2020-07-01_15-42-06_chemotaxisl_worm4-TablePosRecord.txt'] is 2  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             22.932267        24.917810        22.369955        24.064411
1             22.932514        24.940295        22.353118        24.071220
2             23.031569        25.139416        22.452418        24.270176
3             23.031252        25.139452        22.452418        24.270765
4             23.031052        25.139452        22.452418        24.271701
...                 ...              ...              ...              ...
199996         6.324418        28.541339         7.033619        27.735396
199997         6.324118        28.541835         7.033319        27.735887
199998         6.323718        28.542126         7.032919        27.735921
199999         6.323418        28.542478         7.032619        27.736183
200000         6.323672        28.542617         7.033421        27.735825

        x_center  y_center      seconds
0        22.6331   24.5573     0.000000
1        22.6334   24.5578     0.005988
2        22.7327   24.7567     0.011976
3        22.7327   24.7567     0.017964
4        22.7327   24.7567     0.023952
...          ...       ...          ...
199996    6.7772   28.1357  1197.580838
199997    6.7769   28.1362  1197.586826
199998    6.7765   28.1365  1197.592814
199999    6.7762   28.1370  1197.598802
200000    6.7759   28.1373  1197.604790

[200001 rows x 7 columns]
7 : x ref of  2020-07-01_16-20-36_chemotaxisl_worm5-TablePosRecord is:  6.6
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_16-20-36_chemotaxisl_worm5-TablePosRecord/2020-07-01_16-20-36_chemotaxisl_worm5-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             26.994574        17.368116        26.400538        16.501134
1             27.089176        17.571956        26.532550        16.703398
2             27.087066        17.572271        26.531966        16.704244
3             27.087066        17.572271        26.531966        16.704244
4             27.087066        17.572271        26.531773        16.704244
...                 ...              ...              ...              ...
199996        13.027672        16.455961        13.945236        16.331422
199997        13.027172        16.455821        13.944771        16.331622
199998        13.026672        16.455783        13.944283        16.331722
199999        13.026172        16.455368        13.943827        16.331097
200000        13.025801        16.454682        13.943428        16.330928

        x_center  y_center      seconds
0        26.6750   16.8426     0.000000
1        26.8076   17.0346     0.005988
2        26.8076   17.0346     0.011976
3        26.8076   17.0346     0.017964
4        26.8076   17.0346     0.023952
...          ...       ...          ...
199996   13.4681   16.4683  1197.580838
199997   13.4676   16.4685  1197.586826
199998   13.4671   16.4686  1197.592814
199999   13.4666   16.4687  1197.598802
200000   13.4662   16.4688  1197.604790

[200001 rows x 7 columns]
8 : x ref of  2020-07-01_17-01-27_chemotaxis_worm6-TablePosRecord is:  9.1
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             24.113237         9.026218        24.772702         9.807346
1             24.111831         9.026424        24.770871         9.808216
2             24.110368         9.026424        24.770833         9.808527
3             24.109364         9.026956        24.770249         9.809257
4             24.107782         9.026363        24.767937         9.808886
...                 ...              ...              ...              ...
199996        -0.215990        15.795618        -0.100571        16.724321
199997        -0.215930        15.795518        -0.100528        16.724221
199998        -0.215930        15.795418        -0.100528        16.724018
199999        -0.215362        15.795118        -0.100230        16.723718
200000        -0.215226        15.794918        -0.099488        16.721767

        x_center  y_center      seconds
0        24.3918    9.3320     0.000000
1        24.3918    9.3320     0.005988
2        24.3918    9.3320     0.011976
3        24.3918    9.3320     0.017964
4        24.3911    9.3314     0.023952
...          ...       ...          ...
199996   -0.0321   16.2026  1197.580838
199997   -0.0321   16.2025  1197.586826
199998   -0.0321   16.2024  1197.592814
199999   -0.0321   16.2021  1197.598802
200000   -0.0321   16.2019  1197.604790

[200001 rows x 7 columns]
9 : x ref of  2020-07-01_17-32-12_control_worm4-TablePosRecord is:  7.639999999999999
['/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/raw_data/2020-07-01_17-32-12_control_worm4-TablePosRecord/2020-07-01_17-32-12_control_worm4-TablePosRecord.txt'] is 1  rows longer
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             19.277886        22.023027        20.269332        22.296426
1             18.862886        21.860394        19.854124        22.101921
2             18.862886        21.860394        19.853507        22.102190
3             18.862886        21.860394        19.853507        22.102458
4             18.862886        21.860394        19.853497        22.102723
...                 ...              ...              ...              ...
199996        15.504924        17.919154        16.182004        17.220461
199997        15.504072        17.917935        16.181131        17.220761
199998        15.503527        17.914982        16.180431        17.220259
199999        15.503014        17.914717        16.179774        17.220674
200000        15.502288        17.914654        16.180577        17.220661

        x_center  y_center      seconds
0        19.7629   22.1274     0.000000
1        19.3479   21.9324     0.005988
2        19.3479   21.9324     0.011976
3        19.3479   21.9324     0.017964
4        19.3479   21.9324     0.023952
...          ...       ...          ...
199996   15.9131   17.5268  1197.580838
199997   15.9121   17.5273  1197.586826
199998   15.9114   17.5278  1197.592814
199999   15.9106   17.5284  1197.598802
200000   15.9098   17.5290  1197.604790

[200001 rows x 7 columns]
10 : x ref of  2020-07-01_17-58-13_control_worm5-TablePosRecord is:  7.639999999999999
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             23.677064        18.024831        23.229153        18.763733
1             23.639121        18.043575        23.228090        18.779829
2             23.639121        18.043575        23.227901        18.780019
3             23.639121        18.043575        23.227665        18.780019
4             23.639521        18.043575        23.227645        18.780951
...                 ...              ...              ...              ...
199996        17.897442        30.185204        18.547477        29.482507
199997        17.897548        30.185704        18.546877        29.483006
199998        17.897692        30.186204        18.546777        29.483151
199999        17.897729        30.186010        18.546277        29.483056
200000        17.898050        30.186259        18.545777        29.483199

        x_center  y_center      seconds
0        23.4864   18.4797     0.000000
1        23.4864   18.4797     0.005988
2        23.4864   18.4797     0.011976
3        23.4864   18.4797     0.017964
4        23.4868   18.4797     0.023952
...          ...       ...          ...
199996   18.1990   29.7569  1197.580838
199997   18.1984   29.7574  1197.586826
199998   18.1983   29.7579  1197.592814
199999   18.1978   29.7584  1197.598802
200000   18.1973   29.7590  1197.604790

[200001 rows x 7 columns]
11 : x ref of  2020-07-01_18-36-25_control_worm6-TablePosRecord is:  7.639999999999999
        absolute_x_Head  absolute_y_Head  absolute_x_Tail  absolute_y_Tail  \
0             21.116013        15.885699        21.122021        15.771337
1             21.112902        15.890795        21.121431        15.776181
2             21.109704        15.896276        21.121102        15.776181
3             21.107674        15.901976        21.120677        15.776814
4             21.103243        15.905595        21.120677        15.777070
...                 ...              ...              ...              ...
199996        17.598849        18.302834        18.382694        18.062414
199997        17.602196        18.302934        18.382555        18.060445
199998        17.602109        18.303034        18.381855        18.060438
199999        17.604549        18.303092        18.381463        18.058875
200000        17.605534        18.302493        18.380863        18.057241

        x_center  y_center      seconds
0        20.9819   15.9909     0.000000
1        20.9819   15.9909     0.005988
2        20.9819   15.9909     0.011976
3        20.9819   15.9909     0.017964
4        20.9819   15.9909     0.023952
...          ...       ...          ...
199996   17.9940   17.9953  1197.580838
199997   17.9934   17.9954  1197.586826
199998   17.9927   17.9955  1197.592814
199999   17.9921   17.9956  1197.598802
200000   17.9915   17.9957  1197.604790

[200001 rows x 7 columns]

## define input and output paths
input--> csv containing absolute coordinates of bodyparts

In [4]:
path='/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/body_part_coordinates/'
output_path='/groups/zimmer/Daniel_Mitic/data/ulises_chemotaxis/'

### define parameters for calculating the gradient

In [5]:
#this is telling you the concentration of every x position occuring in the data
#parameters determined via the curve fit script
L=1
x0=3.81953189
k=-0.69421567
b=0

### loop to add concentration and concentration change for all bodyparts

In [7]:
for filename in natsorted(os.listdir(path)):
    if filename.endswith('.csv'):
        bodypart_coords=pd.read_csv(path+filename)
        
        #calculate concentration
        bodypart_coords=coord_conv.calculate_concentration_for_bodyparts(bodypart_coords.copy(),'sigmoid',L,x0,k,b)
        
        #calculate concentration change
        all_bodyparts_concentration=bodypart_coords[bodypart_coords.columns[pd.Series(bodypart_coords.columns).str.contains('concentration')]]

        #add new columns with change in concentration
        for current_bodypart in all_bodyparts_concentration.columns:
            bodypart_coords[f'change_in_{current_bodypart}']=all_bodyparts_concentration[current_bodypart].diff() 
        
        #for some reason a second index column is added  which i delete here
        bodypart_coords.drop(bodypart_coords.columns[0], axis=1, inplace=True)
     
    #save as csv
    bodypart_coords.to_csv(output_path+filename+'_bodypart_coordinates_concentration.csv',index=False)